config/routes.rb
KwEcovita::Application.routes.draw do |map|

  get "reports/index"

  get "ratings/create"
  
  
  
  namespace(:admin){
    resources :newsletters
    resources :gifts
    resources :users do
      collection do
        get 'search'
      end
    end
    resources :orders
    resources :reports do
      collection do
        get 'seen'
        get 'sold'
      end
    end
    resources :order_products
    resources :product_comments
    resources(:pages){
      resources(:galleries){
        resources :gallery_images
      }
    }
    resources :page_banners
    resources(:banner_categories){
      resources :banners
    }
    resources(:categories){
      resources(:subcategories){
        resources(:products){
          resources :product_comments
          resources :product_images
        }
      }
    }
    resources :searchs  do
      collection do
        get 'results'
        get 'resend' 
        get 'details'  
        get 'sendmail'
      end
      
      member do
        get 'track'
        post 'track'
        post 'save_track'
        get 'save_track'
      end
    end
    
    root :to => "categories#index"
  }
  
  resources(:carrinhos){
    collection do
      get :empty_cart
    end
  }
  
  resources :home
  resources(:produtos){
    member do
      get :add_to_cart
      get :remove_from_cart
      get :add_to_wishlist
      get :remove_from_wishlist
    end
  }
  resources :search  do
    get :autocomplete_product_name, :on => :collection
    collection do
      get 'results'
    end
  end  
  resources :orders
  resources :sitecontacts
  resources :terms
  resources :politics
  resources :deliveries
  resources :product_comments
  resources :categorias
  resources :ratings
  resources :accounts
  resources :banners
  resources :subcategorias
  resources(:wishlists)
  resources :users
  resources :myorders
  resources(:user_sessions){
    collection do
      get :logado
    end
  }
  resources(:payments){
    collection do
      post :efetuado
      get :efetuado
    end
  }
  resources :password_resets
    
  get "static_content/denied"
  get "static_content/index"

  root :to => "home#index"

  
  root :controller => "static_content", :action => "index"

  post "pagseguro_developer", :to => "pag_seguro/developer#create"
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"
end

app/controllers/admin/searchs_controller.rb
class Admin::SearchsController < ApplicationController
  access_control do
    allow :admin, :supervisor
  end
  layout "admin"
  

  def index
    fstatus = ' '
    ftype = ' '
    if !params[:status].blank?
      if (ApplicationController.helpers.traduz_status_do_pedido(params[:status]) != '')
        fstatus = " and status = '"+ params[:status]+"'" 
      end
    end
    if !params[:type].blank?
      if (ApplicationController.helpers.traduz_tipo_do_pagamento(params[:type]) != '')
        ftype = " and payment_type = '"+ params[:type]+"'" 
      end
    end    
    
    @Orders = Order.find( :all,
                          :conditions => ['id > 0'+fstatus+ftype],
                          :order => 'id DESC',
                          :include =>[:user]
                        ).paginate :page => params[:page],:per_page => 50 
  end  

  def show
    fstatus = ' '
    ftype = ' '
    if !params[:status].blank?
      if (ApplicationController.helpers.traduz_status_do_pedido(params[:status]) != '')
        fstatus = " and status = '"+ params[:status]+"'" 
      end
    end
    if !params[:type].blank?
      if (ApplicationController.helpers.traduz_tipo_do_pagamento(params[:type]) != '')
        ftype = " and payment_type = '"+ params[:type]+"'" 
      end
    end    
    
    @Orders = Order.find( :all,
                          :conditions => ['user_id = ?'+fstatus+ftype, params[:id]],
                          :order => 'id DESC',
                          :include =>[:user]
                        ).paginate :page => params[:page],:per_page => 50    
  end

#  def results
#    if !params[:keyword].blank?
#        @Results = Order.find(:all, :conditions => ['id = ?', params[:keyword]])
#        if !@Results.blank?
#          @Results_itens = @Results.first.order_products
#        end
#    end
#  end
  
      
  def results
    if !params[:keyword].blank?
      @Results = Order.search_for(params[:keyword])
      
      if !@Results.blank?
        @Results_itens = @Results.first.order_products
      end
    end
  end
  
  def details
    if !params[:keyword].blank?
      @Results = Order.find(params[:keyword])
      
      if !@Results.blank?
        @Results_itens = @Results.order_products
      end
    end
  end
  
  def resend
    if !params[:cod].blank?
      $Order = Order.all(:conditions=>['id = ? and ((status = "completed") or (status = "approved"))',params[:cod]])
      if $Order.count == 0
        flash[:notice] = "Dados informados são invalidos"
      else
        UserMailer.payment_made($Order.first).deliver
        flash[:notice] = "Email Enviado com sucesso!"
      end
    else
      flash[:notice] = "Erro ao processar os dados, ID não informada!"
    end
  end
  
  def sendmail
    @erro = true
    if !params[:cod].blank?
        @ordersend = Order.all(:conditions => ['id = ?',params[:cod]]) 
        if @ordersend.count > 0
          UserMailer.reports(@ordersend).deliver
          @ordersend.each do |venda|
            venda.order_send_mail = true
            venda.save
          end
          @erro = false      
          classe = ApplicationController.helpers.status_do_pedido(@ordersend.first.status,@ordersend.first.order_send_mail)
          @classe = classe.split("'")
        end
    end
  end
  
  def track
    @order = Order.find(params[:id])
  end
  
  def save_track
    @order = Order.find(params[:order_id])
    @order.rastreamento = params[:code]
    
    if !params[:code].blank?
      if @order.save
        @out = "Código inserido com sucesso!"
      else
        @out = "Falha ao salvar o código"
      end
    else
      @out = "Digite o código!"
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  layout "interna"
  before_filter :load_site_categories,:load_cart  
  require "rails3-jquery-autocomplete"
  autocomplete :product, :name, :full => true
  
  def index
    
  end
  
  def results
    #Se não for passado keyword manda mensagem de erro!
    if (!params[:keyword].blank?)
      #Grava palavra chave para gerar o tagcloud
      @keyword = Keyword.new
      @keyword.tag_list = params[:keyword]
      @keyword.save
      
      key = "%"+params[:keyword]+"%"

      #Se não for passado a categoria irá carregar todas!
      if !params[:category].blank? 
        cat = " and `categories`.`id` = '"+ params[:category]+"'"
      else
        cat = ' '
      end
      #Se não for passado order irá ordenar pelo campo views
      if !params[:order].blank? 
        case params[:order]
          when '1'
            order = 'views'
          when '2'
            order = 'price'
          when '3'
            order = 'price DESC'
          when '4'
            order = 'name'     
          else
            order = 'views'
        end
      else
        order = 'views'
      end
      #Se não for passado a quantidade de itens por pagina usar 5
      if !params[:pag].blank? 
        qtdade = params[:pag]
      else
        qtdade = '10'
      end      
      @Results = Product.find(:all,
                              :select=> "`products`.*, `subcategories`.`name` as scatname,`categories`.`id` as catid ,`categories`.`name` as catname ",
                              :joins=>"`products` INNER JOIN `subcategories` ON `products`.`subcategory_id` = `subcategories`.`id` INNER JOIN `categories` ON `subcategories`.`category_id` = `categories`.`id` ",
                              :conditions=>["(`products`.`name` like ? or `products`.`summary` like ? or `products`.`description` like ?) AND price > 0 AND IF(`products`.`stock_control` = 1, `products`.`stock_quantity` > 0 AND published = 1,  published = 1)"+cat,key,key,key],
                              :order=> order
                              ).paginate(:page => params[:page], :per_page => qtdade)
    else
      flash[:error] = "Os dados enviados para consulta são invalidos!"
    end
  end
  
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/searchs/_info.html.erb
<%content_for :head do%>
	<%= javascript_include_tag "jquery.js" %>
	<%= javascript_include_tag "jquery.tablesorter.min.js" %>
	
	<script>
	jQuery.noConflict();
	
	jQuery(document).ready(function() 
	    { 
	        jQuery("table").tablesorter(); 
	    } 
	);
	</script>
	
<% end %>
<div style="margin-bottom:20px;">
	<div id="search" style="display:block;float:left;">
		<p>Informe o número da autorização do Pag Seguro</p>
		<%=form_tag '/admin/searchs/results', :method => :get, :name=>"formkeyword"%>
			<%=text_field_tag :keyword, nil ,:style => "width:400px;"%>
			<%=submit_tag "Buscar"%>
		</form>
	</div>
	<div id="filtrar" style="display:block;float:right;">
		<% if $pag == 0 %>
			<%=form_tag '/admin/searchs', :method => :get %>
		<% else %>
			<%=form_tag '/admin/searchs/'+params[:id], :method => :get %>		
		<% end %>
		<label style=" vertical-align:middle; text-align:left;">Filtrar por Status:</label>
          <select name="status" id="status"style=" text-align:left;">
              <option value>Todos</option>
              <option value="completed">Completo</option>
              <option value="incompleted">Incompleto</option>
              <option value="pending">Aguardando Pagamento</option>
              <option value="approved">Aprovado</option>
              <option value="verifying">Em Análise</option>
              <option value="canceled">Cancelado</option>
              <option value="refunded">Devolvido</option>
          </select><br />
          <label style=" vertical-align:middle; text-align:left;">Tipo de Pagamento:</label>
          <select name="type" id="type" style=" text-align:left; margin-right:10px;">
              <option value>Todos</option>
              <option value="credit_card">Cartão de Crédito</option>
              <option value="invoice">Boleto</option>
              <option value="pagseguro">Transferência entre Pagseguro</option>
              <option value="online_transfer">Pagamento Online</option>
              <option value="donation">Doação</option>
          </select><br /><br />
		<%= submit_tag "Filtrar...", :style=>"text-align:right;" %>
		</form>
	</div>
<div class="clear"></div>
</div>
<br />
<div id="orders">
	<table cellspacing="0" class="tablesorter" id="table_user">
		<thead> 
			<tr>
				<th width="70px">Ordem</th>
			    <th width="250px">Usuário</th>
			    <th width="150px">Status</th>
			    <th width="150px">Tipo de Pagamento</th>
			    <th width="100px">Enviado p/ Manipular</th>	
			    <th width="200px">ID Pagseguro</th>
			</tr>
		</thead> 
		<tbody>
	  	<% for order in @Orders %>
	    <tr id="tr_show_<%=order.id%>"<%=status_do_pedido(order.status,order.order_send_mail) %>>
		  <td align="center"><%= order.id %></td>
	      <td><%= order.user.nome %></td>
	      <td align="center"><%= traduz_status_do_pedido(order.status) %></td>
	      <td align="center"><%= traduz_tipo_do_pagamento(order.payment_type) %></td>
		  <td align="center"><%= print_active(order.order_send_mail)  %><%=raw ("<br />"+ link_to("Enviar email", "/admin/searchs/sendmail?cod="+ order.id.to_s, :remote=>true)) if (order.status == "completed" or order.status == "approved")%></td>
	      <td align="center"><%= link_to(order.pagseguro_id, '/admin/searchs/results?utf8=✓&keyword='+order.pagseguro_id+'&commit=Buscar') if !order.pagseguro_id.blank? %> <%= link_to("Detalhes", '/admin/searchs/details?utf8=✓&keyword='+order.id.to_s+'&commit=Buscar') if order.pagseguro_id.blank? %></td>
	    </tr>
	  <% end %>
	  </tbody>
	</table>
	<br />
	<%= will_paginate @Orders %>
	
</div>
<script>
	document.getElementById('keyword').focus();
</script>

app/views/admin/searchs/details.html.erb
<%if !@Results.blank?%>
	<h2>Busca por: <%=params[:keyword]%></h2>
	<br />
	<br />
	<label>Nome: </label><strong class="f_dados"><%= @Results.user.nome%> <%= @Results.user.sobrenome%></strong><br />
	<label>E-mail: </label><strong class="f_dados"><%= @Results.user.email%></strong><br />
	<label>CPF: </label><strong class="f_dados"><%= @Results.user.cpf%></strong><br />
	<label>RG: </label><strong class="f_dados"><%= @Results.user.rg%></strong><br />	
	<label>Endereço: </label><strong class="f_dados"><%= @Results.street%>, <%= @Results.number%> <%= " - " + @Results.complement if !@Results.complement.blank?%> </strong><br />
	<label>Bairro: </label><strong class="f_dados"><%= @Results.neighbourood %></strong><br />		
	<label>Cidade: </label><strong class="f_dados"><%= @Results.city%>-<%= @Results.state%></strong><br />
	<label>CEP: </label><strong class="f_dados"><%= @Results.zipcode%></strong><br />		
	<label>Telefone: </label><strong class="f_dados"><%= @Results.user.phone%> / <%= @Results.user.cellphone%></strong><br />				
	<br />
	<br />
	<label>Status: </label><strong class="f_dados"><%= traduz_status_do_pedido(@Results.status)%></strong><br />
	<label>Tipo de Pagameto: </label><strong class="f_dados"><%= traduz_tipo_do_pagamento(@Results.payment_type)%></strong><br />
	<label>Tipo de Envio: </label><strong class="f_dados"><%= @Results.shipping%></strong><br />
	<label>Código Rastreamento: </label><strong class="f_dados"><%= @Results.rastreamento%></strong> <br />
	<br />

	<br />
	<br />	
	<table border="1" align="center">
		<tr>
		    <th width="300px">Produto</th>
		    <th width="120px">Quantidade</th>
		    <th width="200px">Unitário</th>
		    <th width="250px">Total</th>
	  </tr>
	<%
		$totalgeral = 0
		$total_parcial = 0
	%>
	<% @Results_itens.each do |item| %>
		<tr>
			<td align="center"><%= item.product.name %> - <%= item.product.features %></td>
			<td align="center"><%= item.amount %></td>
			<td align="center"><%= number_to_currency(item.price / item.amount) %></td>
			<td align="center"><%=number_to_currency($total_parcial = (item.price))%></td>
		</tr>
	<% $totalgeral += $total_parcial %>
	<%end%>
	</table>
	<br />
	<label>Total: </label><strong class="f_dados"><%= number_to_currency($totalgeral)%></strong><br />
	<br />
	<%= link_to "Voltar", request.env['HTTP_REFERER'] %>
<%else%>
	<h2>Nenhum registro foi localizado!</h2><br/>
	<%= link_to "Voltar", request.env['HTTP_REFERER'] %>
<%end%>

app/views/admin/searchs/index.html.erb
<% $pag = 0 %>
<%= render 'info' %>

app/views/admin/searchs/resend.html.erb
<br />
<br />
<%= link_to "Voltar", admin_searchs_path%>

app/views/admin/searchs/results.html.erb
<%if !@Results.blank?%>
	<h2>Busca por: <%=params[:keyword]%></h2>
	<br />
	<br />
	<label>Nome: </label><strong class="f_dados"><%= @Results.first.user.nome%> <%= @Results.first.user.sobrenome%></strong><br />
	<label>E-mail: </label><strong class="f_dados"><%= @Results.first.user.email%></strong><br />
	<label>CPF: </label><strong class="f_dados"><%= @Results.first.user.cpf%></strong><br />
	<label>RG: </label><strong class="f_dados"><%= @Results.first.user.rg%></strong><br />	
	<label>Endereço: </label><strong class="f_dados"><%= @Results.first.street%>, <%= @Results.first.number%> <%= " - " + @Results.first.complement if !@Results.first.complement.blank?%> </strong><br />
	<label>Bairro: </label><strong class="f_dados"><%= @Results.first.neighbourood %></strong><br />		
	<label>Cidade: </label><strong class="f_dados"><%= @Results.first.city%>-<%= @Results.first.state%></strong><br />
	<label>CEP: </label><strong class="f_dados"><%= @Results.first.zipcode%></strong><br />		
	<label>Telefone: </label><strong class="f_dados"><%= @Results.first.area_code%><%= @Results.first.phone%></strong><br />				
	<br />
	<br />
	<label>Status: </label><strong class="f_dados"><%= traduz_status_do_pedido(@Results.first.status)%></strong><br />
	<label>Tipo de Pagameto: </label><strong class="f_dados"><%= traduz_tipo_do_pagamento(@Results.first.payment_type)%></strong><br />
	<label>Tipo de Envio: </label><strong class="f_dados"><%= @Results.first.shipping%></strong><br />
	<label>Código Rastreamento: </label><strong class="f_dados"><%= @Results.first.rastreamento%></strong> | <%= link_to "Inserir/ Alterar Codigo de Rastreamento", track_admin_search_path(@Results.first.id)%><br />
	<br />
	<br />
	<%= link_to "Reenviar email para cliente", "/admin/searchs/resend?cod="+ @Results.first.id.to_s%>
	<br />
	<br />	
	<table border="1" align="center">
		<tr>
		    <th width="300px">Produto</th>
		    <th width="120px">Quantidade</th>
		    <th width="200px">Unitário</th>
		    <th width="250px">Total</th>
	  </tr>
	<%
		$totalgeral = 0
		$total_parcial = 0
	%>
	<% @Results_itens.each do |item| %>
		<tr>
			<td align="center"><%= item.product.name %> - <%= item.product.features %></td>
			<td align="center"><%= item.amount %></td>
			<td align="center"><%= number_to_currency(item.price / item.amount) %></td>
			<td align="center"><%=number_to_currency($total_parcial = (item.price))%></td>
		</tr>
	<% $totalgeral += $total_parcial %>
	<%end%>
	</table>
	<br />
	<label>Total: </label><strong class="f_dados"><%= number_to_currency($totalgeral)%></strong><br />
	<br />
	<%= link_to "Voltar", request.env['HTTP_REFERER'] %>
<%else%>
	<h2>Nenhum registro foi localizado!</h2><br/>
	<%= link_to "Voltar", request.env['HTTP_REFERER'] %>
<%end%>

app/views/admin/searchs/save_track.js.erb
alert('<%=@out%>')

var out = '<%=@out%>'
if (out = 'Código inserido com sucesso!')
{
	window.location.href = '/admin/searchs'
}

app/views/admin/searchs/sendmail.js.erb
<% if !@erro%>
	aclasse = "<%= @classe[1] %>";
	update = "";	
	update += "  <td align='center'>SS<%= @ordersend.first.id %></td>";
	update += "  <td><%= @ordersend.first.user.nome %></td>";
	update += "  <td align='center'><%= traduz_status_do_pedido(@ordersend.first.status) %></td>";
	update += "  <td align='center'><%= traduz_tipo_do_pagamento(@ordersend.first.payment_type) %></td>";
	update += "  <td align='center'><%= print_active(@ordersend.first.order_send_mail)  %><%=raw escape_javascript ('<br />'+ link_to('Reenviar email', '/admin/searchs/sendmail?cod='+ @ordersend.first.id.to_s, :remote=>true)) if (@ordersend.first.status == 'completed' or @ordersend.first.status == 'approved')%></td>";
	update += "  <td align='center'><%= escape_javascript (link_to(@ordersend.first.pagseguro_id, '/admin/searchs/results?utf8=✓&keyword='+ @ordersend.first.pagseguro_id+'&commit=Buscar')) if !@ordersend.first.pagseguro_id.blank? %> <%= escape_javascript(link_to('Detalhes', '/admin/searchs/details?utf8=✓&keyword='+ @ordersend.first.id.to_s+'&commit=Buscar')) if @ordersend.first.pagseguro_id.blank? %></td>";
	jQuery('#tr_show_<%=@ordersend.first.id%>').removeClass().addClass(aclasse);
	jQuery('#tr_show_<%=@ordersend.first.id%>').html(update);
	alert('Email enviado com sucesso!');
<% else %>
	alert("Ocorreu um erro ao processar a requisição");
<% end %>

app/views/admin/searchs/show.html.erb
<% $pag = 1 %>
<%= render 'info' %>
<br />
<br />
<%= link_to "Voltar", admin_users_path %>

app/views/admin/searchs/track.html.erb
<% title "Inserir código de rastreamento" %>

<p><strong>AVISO:</strong> depois de inserido o código, o status do pedido será alterado automaticamente para ENVIADO.</p>

<%=form_tag save_track_admin_search_path(@order), :remote => :true, :method => :post%>
	<%=text_field_tag :code, @order.rastreamento%>
	<%=hidden_field_tag :order_id, @order.id%>
	<%=submit_tag "Enviar"%>
</form>