config/routes.rb
KwEcovita::Application.routes.draw do |map|

  get "reports/index"

  get "ratings/create"
  
  
  
  namespace(:admin){
    resources :newsletters
    resources :gifts
    resources :users do
      collection do
        get 'search'
      end
    end
    resources :orders
    resources :reports do
      collection do
        get 'seen'
        get 'sold'
      end
    end
    resources :order_products
    resources :product_comments
    resources(:pages){
      resources(:galleries){
        resources :gallery_images
      }
    }
    resources :page_banners
    resources(:banner_categories){
      resources :banners
    }
    resources(:categories){
      resources(:subcategories){
        resources(:products){
          resources :product_comments
          resources :product_images
        }
      }
    }
    resources :searchs  do
      collection do
        get 'results'
        get 'resend' 
        get 'details'  
        get 'sendmail'
      end
      
      member do
        get 'track'
        post 'track'
        post 'save_track'
        get 'save_track'
      end
    end
    
    root :to => "categories#index"
  }
  
  resources(:carrinhos){
    collection do
      get :empty_cart
    end
  }
  
  resources :home
  resources(:produtos){
    member do
      get :add_to_cart
      get :remove_from_cart
      get :add_to_wishlist
      get :remove_from_wishlist
    end
  }
  resources :search  do
    get :autocomplete_product_name, :on => :collection
    collection do
      get 'results'
    end
  end  
  resources :orders
  resources :sitecontacts
  resources :terms
  resources :politics
  resources :deliveries
  resources :product_comments
  resources :categorias
  resources :ratings
  resources :accounts
  resources :banners
  resources :subcategorias
  resources(:wishlists)
  resources :users
  resources :myorders
  resources(:user_sessions){
    collection do
      get :logado
    end
  }
  resources(:payments){
    collection do
      post :efetuado
      get :efetuado
    end
  }
  resources :password_resets
    
  get "static_content/denied"
  get "static_content/index"

  root :to => "home#index"

  
  root :controller => "static_content", :action => "index"

  post "pagseguro_developer", :to => "pag_seguro/developer#create"
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_products, :dependent => :destroy
  
  scoped_search :in => :user, :on => [:nome, :sobrenome, :email]
  scoped_search :on => [:pagseguro_id]
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  access_control do
    allow :admin, :supervisor
  end
  
  layout "admin"
  
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    if @order.save
      redirect_to @order, :notice => "Successfully created order."
    else
      render :action => 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      redirect_to @order, :notice  => "Successfully updated order."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_url, :notice => "Successfully destroyed order."
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :load_site_categories, :load_cart
  layout "interna"
  
  def new
    
  end
  
  def create
    @order = Order.new
    #GRAVAR TRANSACAO NO BANCO , OS ITENS COMPRADOS ESTAO GRAVADOS NO CARRINHO
    #VERIFICA SE EXISTE A TRANSACAO
    @order.user_id = current_user.id
    @order.status = "incompleted"
    
    if !@order.save
      #erro
      flash[:notice] = "Erro ao gravar transação"
    else
      #GERAR PEDIDO
      @order_product = PagSeguro::Order.new(@order.id)
      #PEGA ITENS DO CARRINHO E ADICIONA AO PEDIDO E FINALIZA
      
      if !@cart.items.blank?
        for cart_item in @cart.items
          @pedidos = @order.order_products.build
          @pedidos.product_id = cart_item.id_product
          @pedidos.amount = cart_item.quantity
          @pedidos.price = cart_item.price
          @pedidos.save
          
          @order_product.billing = {
            :name                  => current_user.nome,
            :email                 => current_user.email
          }
          
          @order_product.add :id => cart_item.id_product, :weight => 0.250, :price => (cart_item.price/cart_item.quantity), :description => cart_item.title, :quantity => cart_item.quantity 
        
          
        end
      end
    end
  
    #LIMPA CARRINHO
    session[:cart] = nil
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for @order do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </p>
  <p>
    <%= f.label :address_id %><br />
    <%= f.text_field :address_id %>
  </p>
  <p>
    <%= f.label :shipping %><br />
    <%= f.text_field :shipping %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/orders/edit.html.erb
<% title "Edit Order" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @order %> |
  <%= link_to "View All", orders_path %>
</p>

app/views/admin/orders/index.html.erb
<% title "Orders" %>

<table>
  <tr>
    <th>User</th>
    <th>Status</th>
    <th>Address</th>
    <th>Shipping</th>
  </tr>
  <% for order in @orders %>
    <tr>
      <td><%= order.user_id %></td>
      <td><%= order.status %></td>
      <td><%= order.address_id %></td>
      <td><%= order.shipping %></td>
      <td><%= link_to "Show", order %></td>
      <td><%= link_to "Edit", edit_order_path(order) %></td>
      <td><%= link_to "Destroy", order, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Order", new_order_path %></p>

app/views/admin/orders/new.html.erb
<% title "New Order" %>

<%= render 'form' %>

<p><%= link_to "Back to List", orders_path %></p>

app/views/admin/orders/show.html.erb
<% title "Order" %>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>
<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>
<p>
  <strong>Address:</strong>
  <%= @order.address_id %>
</p>
<p>
  <strong>Shipping:</strong>
  <%= @order.shipping %>
</p>

<p>
  <%= link_to "Edit", edit_order_path(@order) %> |
  <%= link_to "Destroy", @order, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", orders_path %>
</p>