config/routes.rb
KwEcovita::Application.routes.draw do |map|

  get "reports/index"

  get "ratings/create"
  
  
  
  namespace(:admin){
    resources :newsletters
    resources :gifts
    resources :users do
      collection do
        get 'search'
      end
    end
    resources :orders
    resources :reports do
      collection do
        get 'seen'
        get 'sold'
      end
    end
    resources :order_products
    resources :product_comments
    resources(:pages){
      resources(:galleries){
        resources :gallery_images
      }
    }
    resources :page_banners
    resources(:banner_categories){
      resources :banners
    }
    resources(:categories){
      resources(:subcategories){
        resources(:products){
          resources :product_comments
          resources :product_images
        }
      }
    }
    resources :searchs  do
      collection do
        get 'results'
        get 'resend' 
        get 'details'  
        get 'sendmail'
      end
      
      member do
        get 'track'
        post 'track'
        post 'save_track'
        get 'save_track'
      end
    end
    
    root :to => "categories#index"
  }
  
  resources(:carrinhos){
    collection do
      get :empty_cart
    end
  }
  
  resources :home
  resources(:produtos){
    member do
      get :add_to_cart
      get :remove_from_cart
      get :add_to_wishlist
      get :remove_from_wishlist
    end
  }
  resources :search  do
    get :autocomplete_product_name, :on => :collection
    collection do
      get 'results'
    end
  end  
  resources :orders
  resources :sitecontacts
  resources :terms
  resources :politics
  resources :deliveries
  resources :product_comments
  resources :categorias
  resources :ratings
  resources :accounts
  resources :banners
  resources :subcategorias
  resources(:wishlists)
  resources :users
  resources :myorders
  resources(:user_sessions){
    collection do
      get :logado
    end
  }
  resources(:payments){
    collection do
      post :efetuado
      get :efetuado
    end
  }
  resources :password_resets
    
  get "static_content/denied"
  get "static_content/index"

  root :to => "home#index"

  
  root :controller => "static_content", :action => "index"

  post "pagseguro_developer", :to => "pag_seguro/developer#create"
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"
end

app/models/banner_category.rb
class BannerCategory < ActiveRecord::Base
  has_many :banners, :dependent => :destroy
  
  def self.lateral
    BannerCategory.first(:conditions => ['name = ?', 'Lateral'])
  end
  
  def self.home
    BannerCategory.first(:conditions => ['name = ?', 'Home'], :order => "id DESC")
  end
end

app/controllers/admin/banner_categories_controller.rb
class Admin::BannerCategoriesController < ApplicationController
  access_control do
    allow :admin, :supervisor
  end
  
  layout "admin"
  
  def index
    @banner_categories = BannerCategory.all
  end

  def show
    @banner_category = BannerCategory.find(params[:id])
  end

  def new
    @banner_category = BannerCategory.new
  end

  def create
    @banner_category = BannerCategory.new(params[:banner_category])
    if @banner_category.save
      redirect_to admin_banner_category_path(@banner_category), :notice => "Successfully created banner category."
    else
      render :action => 'new'
    end
  end

  def edit
    @banner_category = BannerCategory.find(params[:id])
  end

  def update
    @banner_category = BannerCategory.find(params[:id])
    if @banner_category.update_attributes(params[:banner_category])
      redirect_to admin_banner_category_path(@banner_category), :notice  => "Successfully updated banner category."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @banner_category = BannerCategory.find(params[:id])
    @banner_category.destroy
    redirect_to admin_banner_categories_path, :notice => "Successfully destroyed banner category."
  end
end

app/helpers/admin/banner_categories_helper.rb
module Admin::BannerCategoriesHelper
end

app/views/admin/banner_categories/_form.html.erb
<%= form_for ([:admin, @banner_category]) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/banner_categories/edit.html.erb
<% title "Edit Banner Category" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", admin_banner_category_path(@banner_category) %> |
  <%= link_to "View All", admin_banner_categories_path %>
</p>

app/views/admin/banner_categories/index.html.erb
<% title "Banner Categories" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for banner_category in @banner_categories %>
    <tr>
      <td><%= banner_category.name %></td>
	  <td><%= link_to "Banners", admin_banner_category_banners_path(banner_category) %></td>
      <td><%= link_to "Show", admin_banner_category_path(banner_category) %></td>
      <td><%= link_to "Edit", edit_admin_banner_category_path(banner_category) %></td>
      <td><%= link_to "Destroy", admin_banner_category_path(banner_category), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Banner Category", new_admin_banner_category_path %></p>

app/views/admin/banner_categories/new.html.erb
<% title "New Banner Category" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_banner_categories_path %></p>

app/views/admin/banner_categories/show.html.erb
<% title "Banner Category" %>

<p>
  <strong>Name:</strong>
  <%= @banner_category.name %>
</p>

<p>
  <%= link_to "Edit", edit_admin_banner_category_path(@banner_category) %> |
  <%= link_to "Destroy", admin_banner_category_path(@banner_category), :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_banner_categories_path %>
</p>